# Generated by Django 5.2 on 2025-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
