# Generated by Django 5.2 on 2025-06-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='nombre',
        ),
    ]
