# Generated by Django 5.2 on 2025-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_first_name_customuser_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendida', 'Suspendida'), ('pendiente_eliminacion', 'Pendiente de Eliminación'), ('eliminada', 'Eliminada')], default='activo', max_length=30),
        ),
        migrations.AddField(
            model_name='tienda',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
