# Generated by Django 5.2 on 2025-06-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tienda_estado_tienda_fecha_eliminacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='celular',
        ),
    ]
