# Generated by Django 5.2 on 2025-07-08 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_phone_number_customuser_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('tipoAccion', models.CharField(max_length=100)),
                ('rutaAcceso', models.CharField(max_length=255)),
                ('origenConexion', models.CharField(choices=[('web', 'Web'), ('api_externa', 'API Externa'), ('mobile', 'Móvil')], max_length=100)),
                ('direccionIP', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('resultado', models.CharField(blank=True, choices=[('exito', 'Éxito'), ('fallo', 'Fallo'), ('casi', 'Casi')], max_length=20, null=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
