# Generated by Django 5.2 on 2025-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='logo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/usuarios/perfil/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/tiendas/logos/'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.ImageField(upload_to='media/imagenesProductos/'),
        ),
    ]
