# Generated by Django 5.2 on 2025-08-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_notificacion_seguimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('nuevo_producto', 'Nuevo producto'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.talla'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='common_noti_usuario_83e04a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_creacion'], name='common_noti_fecha_c_c4f901_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['usuario'], name='common_segu_usuario_7b286a_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['tienda'], name='common_segu_tienda__71c7fc_idx'),
        ),
    ]
