# Generated by Django 5.2 on 2025-09-01 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_notificacion_options_alter_seguimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='common.tienda'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas_seguidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
