# Generated by Django 5.2 on 2025-09-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_seguimiento_tienda_alter_seguimiento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='productos', to='common.categoria'),
        ),
    ]
