# Generated by Django 5.2 on 2025-09-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_producto_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='color',
        ),
    ]
