# Generated by Django 5.2 on 2025-08-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilType',
        ),
    ]
